### ISSUE TITLE
Use semantic versioning

### ISSUE THREAD

**Issue by AntoineAugusti** [unusorin/pushbullet#1]
Hey,

First of all, I really appreciate your package and I plan to use it on a project. Could you please release versions of your package, using semantic versioning? It would be awesome for Composer.

Thanks a lot :)

If you need some info about semantic versioning: http://semver.org

**Comment by unusorin** [comment]
This project is very old and I'm not sure it's compliant with the current API specs. If you really need it, I can do a "release"

**Comment by AntoineAugusti** [comment]
I've forked it and really it wasn't so hard to comply with the new version of the API. Nevertheless I've found another package that seems to be quite well: https://github.com/ivkos/PushBullet-for-PHP

Thanks for your work!
